from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

FIRECRAWL_WAIT_FOR_MS = 12000
FIRECRAWL_PAGE_TIMEOUT_MS = 90000
FIRECRAWL_CLIENT_TIMEOUT_SECONDS = 120
FIRECRAWL_MAX_RETRIES = 3
FIRECRAWL_BACKOFF_FACTOR = 1.0
FIRECRAWL_MAX_AGE_MS = 0
FIRECRAWL_CONCURRENCY = 5

CAPTURE_MIN_TEXT = 200
CAPTURE_RETRY_WAIT_MS = 18000

OUTPUT_DIR = BASE_DIR / "extraction_output"
